In [ ]:
import pandas as pd
spotify_data= pd.read_csv(r"/content/SpotifyFeatures.csv")
spotify_data

,genre,artist_name,track_name,track_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,Movie,Henri Salvador,C'est beau de faire un Show,0BRjO6ga9RKCKjfDqeFgWV,0,0.61100,0.389,99373,0.910,0.000000,C#,0.3460,-1.828,Major,0.0525,166.969,4/4,0.814
1,Movie,Martin & les fées,Perdu d'avance (par Gad Elmaleh),0BjC1NfoEOOusryehmNudP,1,0.24600,0.590,137373,0.737,0.000000,F#,0.1510,-5.559,Minor,0.0868,174.003,4/4,0.816
2,Movie,Joseph Williams,Don't Let Me Be Lonely Tonight,0CoSDzoNIKCRs124s9uTVy,3,0.95200,0.663,170267,0.131,0.000000,C,0.1030,-13.879,Minor,0.0362,99.488,5/4,0.368
3,Movie,Henri Salvador,Dis-moi Monsieur Gordon Cooper,0Gc6TVm52BwZD07Ki6tIvf,0,0.70300,0.240,152427,0.326,0.000000,C#,0.0985,-12.178,Major,0.0395,171.758,4/4,0.227
4,Movie,Fabien Nataf,Ouverture,0IuslXpMROHdEPvSl1fTQK,4,0.95000,0.331,82625,0.225,0.123000,F,0.2020,-21.150,Major,0.0456,140.576,4/4,0.390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232720,Soul,Slave,Son Of Slide,2XGLdVl7lGeq8ksM6Al7jT,39,0.00384,0.687,326240,0.714,0.544000,D,0.0845,-10.626,Major,0.0316,115.542,4/4,0.962
232721,Soul,Jr Thomas & The Volcanos,Burning Fire,1qWZdkBl4UVPj9lK6HuuFM,38,0.03290,0.785,282447,0.683,0.000880,E,0.2370,-6.944,Minor,0.0337,113.830,4/4,0.969
232722,Soul,Muddy Waters,(I'm Your) Hoochie Coochie Man,2ziWXUmQLrXTiYjCg2fZ2t,47,0.90100,0.517,166960,0.419,0.000000,D,0.0945,-8.282,Major,0.1480,84.135,4/4,0.813
232723,Soul,R.LUM.R,With My Words,6EFsue2YbIG4Qkq8Zr9Rir,44,0.26200,0.745,222442,0.704,0.000000,A,0.3330,-7.137,Major,0.1460,100.031,4/4,0.489
232724,Soul,Mint Condition,You Don't Have To Hurt No More,34XO9RwPMKjbvRry54QzWn,35,0.09730,0.758,323027,0.470,0.000049,G#,0.0836,-6.708,Minor,0.0287,113.897,4/4,0.479

In [ ]:
spotify_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86519 entries, 0 to 86518
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   genre             86519 non-null  object
 1   artist_name       86519 non-null  object
 2   track_name        86519 non-null  object
 3   track_id          86519 non-null  object
 4   popularity        86519 non-null  int64
 5   acousticness      86519 non-null  float64
 6   danceability      86519 non-null  float64
 7   duration_ms       86519 non-null  int64
 8   energy            86519 non-null  float64
 9   instrumentalness  86519 non-null  float64
 10  key               86519 non-null  object
 11  liveness          86518 non-null  float64
 12  loudness          86518 non-null  float64
 13  mode              86518 non-null  object
 14  speechiness       86518 non-null  float64
 15  tempo             86518 non-null  float64
 16  time_signature    86518 non-null  object
 17  valence           86518 non-null  float64
dtypes: float64(9), int64(2), object(7)
memory usage: 11.9+ MB

In [ ]:

data=spotify_data.drop(["track_id","mode","time_signature","key"],axis=1)
df=data.copy()
df=df.drop(["artist_name","track_name"],1)
df

<ipython-input-53-3357e1c75b22>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df=df.drop(["artist_name","track_name"],1)

,genre,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence
0,Movie,0,0.61100,0.389,99373,0.910,0.000000,0.3460,-1.828,0.0525,166.969,0.814
1,Movie,1,0.24600,0.590,137373,0.737,0.000000,0.1510,-5.559,0.0868,174.003,0.816
2,Movie,3,0.95200,0.663,170267,0.131,0.000000,0.1030,-13.879,0.0362,99.488,0.368
3,Movie,0,0.70300,0.240,152427,0.326,0.000000,0.0985,-12.178,0.0395,171.758,0.227
4,Movie,4,0.95000,0.331,82625,0.225,0.123000,0.2020,-21.150,0.0456,140.576,0.390
...,...,...,...,...,...,...,...,...,...,...,...,...
232720,Soul,39,0.00384,0.687,326240,0.714,0.544000,0.0845,-10.626,0.0316,115.542,0.962
232721,Soul,38,0.03290,0.785,282447,0.683,0.000880,0.2370,-6.944,0.0337,113.830,0.969
232722,Soul,47,0.90100,0.517,166960,0.419,0.000000,0.0945,-8.282,0.1480,84.135,0.813
232723,Soul,44,0.26200,0.745,222442,0.704,0.000000,0.3330,-7.137,0.1460,100.031,0.489
232724,Soul,35,0.09730,0.758,323027,0.470,0.000049,0.0836,-6.708,0.0287,113.897,0.479

In [ ]:
from sklearn.preprocessing import StandardScaler
col = ['popularity', 'acousticness', 'danceability', 'duration_ms',
       'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness',
       'tempo', 'valence']
scaler = StandardScaler()
df[col] = scaler.fit_transform(df[col])
df

,genre,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence
0,Movie,-2.261007,0.683376,-0.890935,-1.141368,1.286908,-0.489819,0.660661,1.290703,-0.367970,1.595607,1.380744
1,Movie,-2.206031,-0.345467,0.191994,-0.821867,0.630249,-0.489819,-0.322835,0.668683,-0.183082,1.823253,1.388435
2,Movie,-2.096080,1.644570,0.585296,-0.545298,-1.669954,-0.489819,-0.564927,-0.718402,-0.455832,-0.588326,-0.334212
3,Movie,-2.261007,0.942701,-1.693703,-0.695295,-0.929789,-0.489819,-0.587623,-0.434817,-0.438044,1.750597,-0.876384
4,Movie,-2.041104,1.638932,-1.203422,-1.282184,-1.313157,-0.083566,-0.065613,-1.930601,-0.405163,0.741433,-0.249618
...,...,...,...,...,...,...,...,...,...,...,...,...
232720,Soul,-0.116961,-1.028056,0.714601,0.766109,0.542948,1.306938,-0.658233,-0.176072,-0.480628,-0.068759,1.949833
232721,Soul,-0.171936,-0.946143,1.242596,0.397901,0.425281,-0.486912,0.110912,0.437780,-0.469308,-0.124166,1.976749
232722,Soul,0.322844,1.500814,-0.201309,-0.573103,-0.576788,-0.489819,-0.607797,0.214712,0.146805,-1.085205,1.376899
232723,Soul,0.157917,-0.300367,1.027088,-0.106615,0.504991,-0.489819,0.595095,0.405603,0.136025,-0.570752,0.131056
232724,Soul,-0.336863,-0.764615,1.097128,0.739094,-0.383207,-0.489657,-0.662772,0.477125,-0.496259,-0.121998,0.092604

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
encoder = OneHotEncoder(sparse=False, handle_unknown="ignore")
enc = pd.DataFrame(encoder.fit_transform(np.array(df["genre"]).reshape(-1,1)))
enc.columns = df["genre"].unique()
enc.head()

,Movie,R&B,A Capella,Alternative,Country,Dance,Electronic,Anime,Folk,Blues,...,Pop,Reggae,Reggaeton,Jazz,Rock,Ska,Comedy,Soul,Soundtrack,World
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df[enc.columns] = enc
df = df.drop("genre",1)
df.head()

<ipython-input-56-d2ccb5cba0ee>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df = df.drop("genre",1)

,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,...,Pop,Reggae,Reggaeton,Jazz,Rock,Ska,Comedy,Soul,Soundtrack,World
0,-2.261007,0.683376,-0.890935,-1.141368,1.286908,-0.489819,0.660661,1.290703,-0.367970,1.595607,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-2.206031,-0.345467,0.191994,-0.821867,0.630249,-0.489819,-0.322835,0.668683,-0.183082,1.823253,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-2.096080,1.644570,0.585296,-0.545298,-1.669954,-0.489819,-0.564927,-0.718402,-0.455832,-0.588326,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-2.261007,0.942701,-1.693703,-0.695295,-0.929789,-0.489819,-0.587623,-0.434817,-0.438044,1.750597,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-2.041104,1.638932,-1.203422,-1.282184,-1.313157,-0.083566,-0.065613,-1.930601,-0.405163,0.741433,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df["name"] = data["track_name"]
df["artist"] = data["artist_name"]

df_2 = df.drop(["artist","name"],1)
df_2

<ipython-input-61-ce4e40c4497a>:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df_2 = df.drop(["artist","name"],1)

,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,...,Pop,Reggae,Reggaeton,Jazz,Rock,Ska,Comedy,Soul,Soundtrack,World
0,-2.261007,0.683376,-0.890935,-1.141368,1.286908,-0.489819,0.660661,1.290703,-0.367970,1.595607,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-2.206031,-0.345467,0.191994,-0.821867,0.630249,-0.489819,-0.322835,0.668683,-0.183082,1.823253,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-2.096080,1.644570,0.585296,-0.545298,-1.669954,-0.489819,-0.564927,-0.718402,-0.455832,-0.588326,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-2.261007,0.942701,-1.693703,-0.695295,-0.929789,-0.489819,-0.587623,-0.434817,-0.438044,1.750597,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-2.041104,1.638932,-1.203422,-1.282184,-1.313157,-0.083566,-0.065613,-1.930601,-0.405163,0.741433,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232720,-0.116961,-1.028056,0.714601,0.766109,0.542948,1.306938,-0.658233,-0.176072,-0.480628,-0.068759,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
232721,-0.171936,-0.946143,1.242596,0.397901,0.425281,-0.486912,0.110912,0.437780,-0.469308,-0.124166,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
232722,0.322844,1.500814,-0.201309,-0.573103,-0.576788,-0.489819,-0.607797,0.214712,0.146805,-1.085205,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
232723,0.157917,-0.300367,1.027088,-0.106615,0.504991,-0.489819,0.595095,0.405603,0.136025,-0.570752,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
232724,-0.336863,-0.764615,1.097128,0.739094,-0.383207,-0.489657,-0.662772,0.477125,-0.496259,-0.121998,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
def find_song(word,artist):
    a = 0
    b = 0
    for i in data["track_name"]:
        if word.lower() in i.lower() and artist.lower() in data["artist_name"][a].lower():
            print("Song Name: ",data["track_name"][a],", Artists: ",data["artist_name"][a])
            b+=1
        a+=1
    if b == 0:
        print("Nothing found. Please try something else :)")
word = "Don't Let Me Be Lonely Tonight"	
artist = "Joseph Williams"
find_song(word,artist)

Song Name:  Don't Let Me Be Lonely Tonight , Artists:  Joseph Williams

In [ ]:
def sim_track_find(word,artist):
    a = 0
    b = 0
    song = []
    indexes = []
    for i in data["track_name"]:
        if word.lower() in i.lower() and artist.lower() in data["artist_name"][a].lower():
            song.append(df_2[a:a+1].values)
            indexes.append(a)
            b+=1
        a+=1
    if b == 0:
        print("Nothing found. Please try something else :)")
        return 0
        
    return song[0][0], indexes[0]

sim_track_find(word,artist)

(array([-2.09607995,  1.6445698 ,  0.58529607, -0.54529771, -1.66995381,
        -0.48981852, -0.56492694, -0.7184024 , -0.45583209, -0.5883258 ,
        -0.33421214,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ]), 2)

In [ ]:
word = "Don't Let Me Be Lonely Tonight"	
artist = "Joseph Williams"

sim_track_find(word,artist)

(array([-2.09607995,  1.6445698 ,  0.58529607, -0.54529771, -1.66995381,
        -0.48981852, -0.56492694, -0.7184024 , -0.45583209, -0.5883258 ,
        -0.33421214,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ]), 2)

In [ ]:
from scipy.spatial import distance
def similar_tracks(data,number,song = "",artist = ""):

    if (sim_track_find(song,artist) == 0):
        return 0
    else:
        x=sim_track_find(song,artist)[0]
        index = sim_track_find(song,artist)[1]
    p = []
    count=0
    for i in df_2.values:
        p.append([distance.cosine(x,i),count])
        count+=1
    p.sort()
    song_names = df["name"]
    artist_names = df["artist"]

    print("\nSimilar songs to ",song_names[index]," by ", artist_names[index],"\n")
    for i in range(1,number+1):
        print(i,"- ",song_names[p[i][1]],", ",artist_names[p[i][1]])
song = "Don't Let Me Be Lonely Tonight"	
artist = "Joseph Williams"
num = 5

similar_tracks(df,int(num),song,artist)

Similar songs to  Don't Let Me Be Lonely Tonight  by  Joseph Williams

1 -  Lonely At The Top ,  Randy Newman
2 -  Solid Gold Cadillac ,  Pearl Bailey
3 -  Le petit Indien ,  Henri Salvador
4 -  Marianne - Single Version ,  Terry Gilkyson
5 -  Against All Odds ,  Joseph Williams